#!/usr/bin/env bash
#Displays "Best School" 8 times, but after 3th, prints "bad luck" and after 8th prints "good luck"i=0
i=0
while (( i <=9))
do
        if (( i == 3))
        then
                echo "bad luck"
        elif ((i == 7))
        then
                echo "good luck"
        else 
                echo "Best School"
        fi
        ((i++))
done
