#!/usr/bin/env bash
#Displays "Best School" 8 times, but after 3th, prints "bad luck" and after 8th prints "good luck"
i=1
while (( i <= 20))
do
        if (( i == 4))
        then
                echo $i
                echo "bad luck from China"
        elif ((i == 8))
        then
                echo $i
                echo "bad luck from Japan"
                
        elif ((i == 17))
        then
                echo $i
                echo "bad luck from Italy"
        else 
                echo $i
        fi
        ((i++))
done
