#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely, creates a PID file and handles signals

cleanup() {
    sudo rm -f /var/run/myscript.pid
    exit 0
}

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap cleanup SIGQUIT

# Correctly write the real script PID as root
sudo bash -c "echo $$ > /var/run/myscript.pid"

while true; do
    echo "To infinity and beyond"
    sleep 2
done
