#!/usr/bin/env bash
#10-process_and_pid_file

pid_file="/var/run/myscript.pid"

# PID fayli
echo $$ > "$pid_file"

trap 'echo "I hate the kill command"; rm -f "$pid_file"; exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$pid_file"; exit 0' SIGQUIT

#loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
