#!/usr/bin/env bash
#Manage my process
PID_FILE="/var/run/my_process.pid"
PROC="./manage_my_process"

start() {
	$PROC &
	echo $! > "$PID_FILE"
	echo "manage_my_process started"
}

stop() {
	if [ -f "$PID_FILE" ];then
		kill "$(cat $PID_FILE)" 2>/dev/null
		rm -f "$PID_FILE"
	fi
	echo "manage_my_process stopped"
}

restart() {
	[ -f "$PID_FILE" ] && kill "$(cat $PID_FILE)" 2>/dev/null && rm -f "$PID_FILE"
	$PROC &
	echo $! > "$PID_FILE"
	echo "manage_my_process restarted"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
